package com.example.testdbbygreendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{
    //新增任务视图2017-10-20
    private final DaoConfig taskViewEntityDaoConfig;
    private final TaskViewEntityDao taskViewEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type,
                      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap)
    {
        super(db);
        //新增任务视图2017-10-20
        taskViewEntityDaoConfig = daoConfigMap.get(TaskViewEntityDao.class).clone();
        taskViewEntityDaoConfig.initIdentityScope(type);

        //新增任务视图2017-10-20
        taskViewEntityDao = new TaskViewEntityDao(taskViewEntityDaoConfig, this);
        //新增任务视图2017-10-20
        registerDao(TaskViewEntity.class, taskViewEntityDao);
    }

    public void clear()
    {
        //新增任务视图2017-10-20
        taskViewEntityDaoConfig.getIdentityScope().clear();
    }


    //新增任务视图2017-10-20
    public TaskViewEntityDao getTaskViewEntityDao()
    {
        return taskViewEntityDao;
    }
}
