package com.example.testdbbygreendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 任务视图
 */
public class TaskViewEntity implements java.io.Serializable {

    /**
     * 主键ID
     */
    private String guid;
    /**
     * 任务ID
     */
    private String taskId;
    /**
     * 产出文档ID
     */
    private String workDocId;
    /**
     * 产出文档标题
     */
    private String docSubject;
    /**
     * 关联文档表的docId
     */
    private String fileId;
    /**
     * 创建用户
     */
    private String createUser;
    /**
     * 创建时间
     */
    private String createDate;
    /**
     * 更新时间
     */
    private String updateDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TaskViewEntity() {
    }

    public TaskViewEntity(String guid) {
        this.guid = guid;
    }

    public TaskViewEntity(String guid, String taskId, String workDocId, String docSubject, String fileId, String createUser, String createDate, String updateDate) {
        this.guid = guid;
        this.taskId = taskId;
        this.workDocId = workDocId;
        this.docSubject = docSubject;
        this.fileId = fileId;
        this.createUser = createUser;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getWorkDocId() {
        return workDocId;
    }

    public void setWorkDocId(String workDocId) {
        this.workDocId = workDocId;
    }

    public String getDocSubject() {
        return docSubject;
    }

    public void setDocSubject(String docSubject) {
        this.docSubject = docSubject;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
